// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TugasMinggu1.Data;

#nullable disable

namespace TugasMinggu1.Data.Migrations
{
    [DbContext(typeof(SwordContext))]
    partial class SwordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElemenSword", b =>
                {
                    b.Property<int>("ElemensElemenId")
                        .HasColumnType("int");

                    b.Property<int>("SwordsId")
                        .HasColumnType("int");

                    b.HasKey("ElemensElemenId", "SwordsId");

                    b.HasIndex("SwordsId");

                    b.ToTable("ElemenSword");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Elemen", b =>
                {
                    b.Property<int>("ElemenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElemenId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElemenId");

                    b.ToTable("Elemens");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Samurais");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Sword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SamuraiId")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SamuraiId");

                    b.ToTable("Swords");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Tipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwordId")
                        .IsUnique();

                    b.ToTable("Tipes");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElemenSword", b =>
                {
                    b.HasOne("TugasMinggu1.Domain.Elemen", null)
                        .WithMany()
                        .HasForeignKey("ElemensElemenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TugasMinggu1.Domain.Sword", null)
                        .WithMany()
                        .HasForeignKey("SwordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Sword", b =>
                {
                    b.HasOne("TugasMinggu1.Domain.Samurai", "Samurai")
                        .WithMany("Swords")
                        .HasForeignKey("SamuraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Samurai");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Tipe", b =>
                {
                    b.HasOne("TugasMinggu1.Domain.Sword", null)
                        .WithOne("Tipes")
                        .HasForeignKey("TugasMinggu1.Domain.Tipe", "SwordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Samurai", b =>
                {
                    b.Navigation("Swords");
                });

            modelBuilder.Entity("TugasMinggu1.Domain.Sword", b =>
                {
                    b.Navigation("Tipes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
